// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIG_DefesaCivil.API.Data.Context;

#nullable disable

namespace SIG_DefesaCivil.API.Migrations
{
    [DbContext(typeof(DefesaCivilDbContext))]
    [Migration("20260304140436_Corrigindo nome errado da coluna de transicoes")]
    partial class Corrigindonomeerradodacolunadetransicoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NaturezaOcorrencia", b =>
                {
                    b.Property<string>("NaturezasId")
                        .HasColumnType("text");

                    b.Property<string>("OcorrenciasId")
                        .HasColumnType("text");

                    b.HasKey("NaturezasId", "OcorrenciasId");

                    b.HasIndex("OcorrenciasId");

                    b.ToTable("OcorrenciaNaturezas", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Data.Models.Ocorrencias.Transicao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEHorario")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EtapaAnteriorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EtapaAtualId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OcorrenciaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EtapaAnteriorId");

                    b.HasIndex("EtapaAtualId");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Trasicoes");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Anexo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataHoraCaptura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdArquivoExterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OcorrenciaId")
                        .HasColumnType("text");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoEntidade")
                        .HasColumnType("integer");

                    b.Property<string>("UrlArmazenamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Etapa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<List<string>>("EtapasDestinoId")
                        .HasColumnType("text[]");

                    b.Property<TimeSpan?>("MaxTempoNaEtapa")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("MinTempoNaEtapa")
                        .HasColumnType("interval");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermissoesParaTransicionarParaEstaEtapa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer");

                    b.Property<string>("QuadroId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuadroId");

                    b.ToTable("Etapas", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Natureza", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CodigoNatureza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("NaturezaPaiId")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NaturezaPaiId");

                    b.ToTable("Naturezas", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataEntradaNaFaseAtual")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EtapaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OcorrenciaPaiId")
                        .HasColumnType("text");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriadorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isVisivel")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("OcorrenciaPaiId");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("Ocorrencias", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.OcorrenciaHistorico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<DateTime>>("Horarios")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone[]");

                    b.Property<string>("OcorrenciaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OcorrenciasHistoricos", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Quadro", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Quadros", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DataAdmissao")
                        .HasColumnType("date");

                    b.Property<string>("DataDeNascimento")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("isAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("isPrimeiroAcesso")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NaturezaOcorrencia", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Natureza", null)
                        .WithMany()
                        .HasForeignKey("NaturezasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", null)
                        .WithMany()
                        .HasForeignKey("OcorrenciasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Data.Models.Ocorrencias.Transicao", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Etapa", "EtapaAnterior")
                        .WithMany()
                        .HasForeignKey("EtapaAnteriorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Etapa", "EtapaAtual")
                        .WithMany()
                        .HasForeignKey("EtapaAtualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany("Transicoes")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtapaAnterior");

                    b.Navigation("EtapaAtual");

                    b.Navigation("Ocorrencia");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Anexo", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", null)
                        .WithMany("Anexos")
                        .HasForeignKey("OcorrenciaId");

                    b.OwnsOne("SIG_DefesaCivil.API.Data.Models.Shared.Endereco", "Localizacao", b1 =>
                        {
                            b1.Property<string>("AnexoId")
                                .HasColumnType("text");

                            b1.Property<string>("Bairro")
                                .HasColumnType("text");

                            b1.Property<string>("CEP")
                                .HasColumnType("text");

                            b1.Property<string>("Complemento")
                                .HasColumnType("text");

                            b1.Property<string>("Latitude")
                                .HasColumnType("text");

                            b1.Property<string>("Longitude")
                                .HasColumnType("text");

                            b1.Property<string>("Numero")
                                .HasColumnType("text");

                            b1.Property<string>("Rua")
                                .HasColumnType("text");

                            b1.HasKey("AnexoId");

                            b1.ToTable("Anexos");

                            b1.WithOwner()
                                .HasForeignKey("AnexoId");
                        });

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Etapa", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Quadro", "Quadro")
                        .WithMany("Etapas")
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quadro");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Natureza", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Natureza", "NaturezaPai")
                        .WithMany("SubNaturezas")
                        .HasForeignKey("NaturezaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NaturezaPai");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Etapa", "Etapa")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", "OcorrenciaPai")
                        .WithMany("SubOcorrencias")
                        .HasForeignKey("OcorrenciaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", "UsuarioCriador")
                        .WithMany("OcorrenciasCriados")
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SIG_DefesaCivil.API.Data.Models.Shared.OcorrenciaCampos", "Campos", b1 =>
                        {
                            b1.Property<string>("OcorrenciaId")
                                .HasColumnType("text");

                            b1.Property<string>("AnalisePreliminar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AreasAfetadas")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CaracterizacaoDoLocal")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("DataEHoraDoOcorrido")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<DateTime?>("DataEHoraInicioAtendimento")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<DateTime?>("DataEHoraTerminoAtendimento")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("Edificacao")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Estrutura")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("GrauDeRisco")
                                .HasColumnType("text");

                            b1.Property<string>("Motivacao")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("NumeroDeAdultos")
                                .HasColumnType("integer");

                            b1.Property<int?>("NumeroDeComodos")
                                .HasColumnType("integer");

                            b1.Property<int?>("NumeroDeCriancas")
                                .HasColumnType("integer");

                            b1.Property<int?>("NumeroDeDeficientes")
                                .HasColumnType("integer");

                            b1.Property<int?>("NumeroDeIdosos")
                                .HasColumnType("integer");

                            b1.Property<int?>("NumeroDeMoradias")
                                .HasColumnType("integer");

                            b1.Property<int?>("NumeroDePavimentos")
                                .HasColumnType("integer");

                            b1.Property<string>("PossuiIPTU")
                                .HasColumnType("text");

                            b1.Property<bool?>("PossuiUnidadeFamiliar")
                                .HasColumnType("boolean");

                            b1.Property<string>("RegimeDeOcupacaoDoImovel")
                                .HasColumnType("text");

                            b1.Property<string>("SolicitanteCPF")
                                .HasColumnType("text");

                            b1.Property<string>("SolicitanteNome")
                                .HasColumnType("text");

                            b1.Property<string>("SolicitanteRG")
                                .HasColumnType("text");

                            b1.Property<string>("TipificacaoDaOcorrencia")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TipoDeRisco")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("OcorrenciaId");

                            b1.ToTable("Ocorrencias");

                            b1.WithOwner()
                                .HasForeignKey("OcorrenciaId");

                            b1.OwnsOne("SIG_DefesaCivil.API.Data.Models.Shared.Endereco", "Localizacao", b2 =>
                                {
                                    b2.Property<string>("OcorrenciaCamposOcorrenciaId")
                                        .HasColumnType("text");

                                    b2.Property<string>("Bairro")
                                        .HasColumnType("text");

                                    b2.Property<string>("CEP")
                                        .HasColumnType("text");

                                    b2.Property<string>("Complemento")
                                        .HasColumnType("text");

                                    b2.Property<string>("Latitude")
                                        .HasColumnType("text");

                                    b2.Property<string>("Longitude")
                                        .HasColumnType("text");

                                    b2.Property<string>("Numero")
                                        .HasColumnType("text");

                                    b2.Property<string>("Rua")
                                        .HasColumnType("text");

                                    b2.HasKey("OcorrenciaCamposOcorrenciaId");

                                    b2.ToTable("Ocorrencias");

                                    b2.WithOwner()
                                        .HasForeignKey("OcorrenciaCamposOcorrenciaId");
                                });

                            b1.Navigation("Localizacao")
                                .IsRequired();
                        });

                    b.Navigation("Campos")
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("OcorrenciaPai");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.OcorrenciaHistorico", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany()
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.RefreshToken", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Etapa", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Natureza", b =>
                {
                    b.Navigation("SubNaturezas");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("SubOcorrencias");

                    b.Navigation("Transicoes");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Quadro", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Usuario", b =>
                {
                    b.Navigation("OcorrenciasCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
