// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIG_DefesaCivil.API.Data.Context;

#nullable disable

namespace SIG_DefesaCivil.API.Migrations
{
    [DbContext(typeof(DefesaCivilDbContext))]
    [Migration("20251228130610_Adicionando tempo máximo na etapa")]
    partial class Adicionandotempomáximonaetapa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NaturezaOcorrencia", b =>
                {
                    b.Property<string>("NaturezasId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OcorrenciasId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NaturezasId", "OcorrenciasId");

                    b.HasIndex("OcorrenciasId");

                    b.ToTable("OcorrenciaNaturezas", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Anexo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdArquivoExterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OcorrenciaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UrlArmazenamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("EntidadeId", "TipoEntidade");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Etapa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtapasDestinoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("MaxTempoNaEtapa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("MinTempoNaEtapa")
                        .HasColumnType("time");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissoesParaTransicionarParaEstaEtapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.Property<string>("QuadroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuadroId");

                    b.ToTable("Etapas", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Natureza", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoNatureza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaturezaPaiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NaturezaPaiId");

                    b.ToTable("Naturezas");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnalisePreliminar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreasAfetadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaracterizacaoDoLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataEHoraDoOcorrido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEHoraInicioAtendimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEHoraTerminoAtendimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEntradaNaFaseAtual")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoCEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoComplemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoRua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estrutura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtapaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GrauDeRisco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDeAdultos")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDeComodos")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDeCriancas")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDeDeficientes")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDeIdosos")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDeMoradias")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDePavimentos")
                        .HasColumnType("int");

                    b.Property<string>("OcorrenciaPaiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PossuiIPTU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PossuiUnidadeFamiliar")
                        .HasColumnType("bit");

                    b.Property<string>("RegimeDeOcupacaoDoImovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitanteCPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitanteNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitanteRG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipificacaoDaOcorrencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeRisco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCriadorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isVisible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("OcorrenciaPaiId");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("Ocorrencias", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.OcorrenciaHistorico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OcorrenciaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OcorrenciasHistoricos", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Quadro", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Quadros", (string)null);
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DataAdmissao")
                        .HasColumnType("date");

                    b.Property<string>("DataDeNascimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("isAtivo")
                        .HasColumnType("bit");

                    b.Property<bool>("isPrimeiroAcesso")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NaturezaOcorrencia", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Natureza", null)
                        .WithMany()
                        .HasForeignKey("NaturezasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", null)
                        .WithMany()
                        .HasForeignKey("OcorrenciasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Anexo", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", null)
                        .WithMany("Anexos")
                        .HasForeignKey("OcorrenciaId");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Etapa", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Quadro", "Quadro")
                        .WithMany("Etapas")
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quadro");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Natureza", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Natureza", "NaturezaPai")
                        .WithMany("SubNaturezas")
                        .HasForeignKey("NaturezaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NaturezaPai");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Etapa", "Etapa")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", "OcorrenciaPai")
                        .WithMany("SubOcorrencias")
                        .HasForeignKey("OcorrenciaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", "UsuarioCriador")
                        .WithMany("OcorrenciasCriados")
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("OcorrenciaPai");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.OcorrenciaHistorico", b =>
                {
                    b.HasOne("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany()
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_DefesaCivil.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Etapa", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Natureza", b =>
                {
                    b.Navigation("SubNaturezas");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Ocorrencia.Ocorrencia", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("SubOcorrencias");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Quadro", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("SIG_DefesaCivil.API.Models.Usuario", b =>
                {
                    b.Navigation("OcorrenciasCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
